language: php

php:
    - 5.3
    - 5.5

env:
    - WP_VERSION=master WP_MULTISITE=0 WP_CF7_VERSION=trunk
    - WP_VERSION=master WP_MULTISITE=1 WP_CF7_VERSION=trunk
    - WP_VERSION=3.5.1 WP_MULTISITE=0 WP_CF7_VERSION=trunk
    - WP_VERSION=master WP_MULTISITE=0 WP_CF7_VERSION=tags/3.4.2
    - WP_VERSION=master WP_MULTISITE=0 WP_CF7_VERSION=tags/3.0

before_script:
    - export WP_TESTS_DIR=/tmp/wordpress-tests/
    - bash bin/install-wp-tests.sh wordpress_test root '' $WP_VERSION 

script: phpunit
